// markets
export const MARKETS_LIST_FETCH = 'MARKETS_LIST_FETCH';
export const MARKETS_LIST_DATA = 'MARKETS_LIST_DATA';
export const MARKETS_LIST_ERROR = 'MARKETS_LIST_ERROR';
export const MARKET_DATA = 'MARKET_DATA';

export const MARKET_ERROR = 'MARKET_ERROR';
export const MARKET_UPDATE_FETCH = 'MARKET_UPDATE_FETCH';
export const MARKET_UPDATE_DATA = 'MARKET_UPDATE_DATA';
export const MARKET_UPDATE_ERROR = 'MARKET_UPDATE_ERROR';
