export const ORDERS_CANCEL_ALL_FETCH = 'orders/ORDERS_CANCEL_ALL_FETCH';
export const ORDERS_CANCEL_ALL_DATA = 'orders/ORDERS_CANCEL_ALL_DATA';
export const ORDERS_CANCEL_ALL_ERROR = 'orders/ORDERS_CANCEL_ALL_ERROR';

export const ORDER_CANCEL_FETCH = 'orders/CANCEL_FETCH';
export const ORDER_CANCEL_DATA = 'orders/CANCEL_DATA';
export const ORDER_CANCEL_ERROR = 'orders/CANCEL_ERROR';

export const ORDER_EXECUTE_FETCH = 'orders/EXECUTE_FETCH';
export const ORDER_EXECUTE_DATA= 'orders/EXECUTE_DATA';
export const ORDER_EXECUTE_ERROR = 'orders/EXECUTE_ERROR';

export const USER_ORDERS_FETCH = 'orders/USER_ORDERS_FETCH';
export const USER_ORDERS_DATA = 'orders/USER_ORDERS_DATA';
export const USER_ORDERS_UPDATE = 'orders/USER_ORDERS_UPDATE';
export const USER_ORDERS_ERROR = 'orders/USER_ORDERS_ERROR';

export const USER_ORDERS_ALL_FETCH = 'orders/USER_ORDERS_ALL_FETCH';
export const USER_ORDERS_ALL_DATA = 'orders/USER_ORDERS_ALL_DATA';
export const USER_ORDERS_ALL_ERROR = 'orders/USER_ORDERS_ALL_ERROR';
