---
kind: pipeline
name: "New version"

concurrency:
  limit: 2

steps:
  # - name: "Test"
  #   image: node:12.13.1
  #   commands:
  #     - cd web
  #     - npm -g install yarn
  #     - yarn install
  #     - yarn lint
  #     - yarn test:ci --collectCoverage=true

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

  - name: "Build Docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
      environment:
        REACT_APP_SENTRY_KEY:
          from_secret: master_sentry_key
        REACT_APP_SENTRY_ORGANIZATION:
          from_secret: master_sentry_organization
        REACT_APP_SENTRY_PROJECT:
          from_secret: master_sentry_project

trigger:
  branch:
    - master
    - "*-stable"
  event:
    - push

image_pull_secrets:
  - dockerconfigjson

---
kind: pipeline
name: "Build branches"

concurrency:
  limit: 2

steps:
  - name: "Build Docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
      tags: ${DRONE_COMMIT:0:7}

trigger:
  branch:
    - "enhancement/*"
    - "feat/*"
    - "feature/*"

  event:
    - push

image_pull_secrets:
  - dockerconfigjson
