---
kind: pipeline
name: "New version"

concurrency:
  limit: 2

steps:
  - name: "Test"
    image: node:12.13.1
    commands:
      - cd web
      - npm -g install yarn
      - yarn install
      - yarn lint
      - yarn test:ci --collectCoverage=true

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

  - name: "Build Docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo:
        from_secret: quay_repo
      registry: quay.io
      environment:
        REACT_APP_SENTRY_KEY:
          from_secret: master_sentry_key
        REACT_APP_SENTRY_ORGANIZATION:
          from_secret: master_sentry_organization
        REACT_APP_SENTRY_PROJECT:
          from_secret: master_sentry_project

  - name: "Push and Notify"
    image: quay.io/openware/sdk-citools:2.6.7
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      SDK_BRANCH: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      TELEGRAM_BOT_TOKEN:
        from_secret: baseapp_telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: baseapp_telegram_chat_id
      SLACK_TOKEN:
        from_secret: baseapp_slack_token
      SLACK_CHANNEL:
        from_secret: baseapp_slack_channel
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
    when:
      branch:
        - master
        - "*-stable"

  # http://plugins.drone.io/drone-plugins/drone-slack/
  - name: Slack Notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel:
        from_secret: slack_webhook_channel
      template: >
        *{{uppercasefirst repo.name}}*
        {{#success build.status}}
         [SUCCESS] Branch {{ build.branch }} by {{ build.author }}. Good job.
        {{else}}
         [FAILURE] Branch {{ build.branch }} by {{ build.author }}. Fix me please.
        {{/success}}
    when:
      branch:
        - master
        - "*-stable"

  - name: "Update global OpenDAX version"
    image: quay.io/openware/goci:0.0.11
    environment:
      GIT_TOKEN:
        from_secret: kite_bot_key
    commands:
      - /app/goci -component=sonic versions
    when:
      branch:
        - "*-stable"

  - name: "Build custom baseapp with assembly line"
    image: curlimages/curl
    environment:
      SERVER: https://ci.openware.work
      REPO: openware/assembly-line
      COMPONENT: baseapp
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - COMPONENT_VERSION=$(cat .tags)
      - "curl -s -XPOST -H \"Authorization: Bearer $DRONE_TOKEN\" -i \"$SERVER/api/repos/$REPO/builds?branch=$DRONE_BRANCH&ASSEMBLY_COMPONENT_VERSION=$COMPONENT_VERSION&ASSEMBLY_COMPONENT=$COMPONENT\""

trigger:
  branch:
    - master
    - "*-stable"
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
