export const WALLETS_FETCH = 'wallets/WALLETS_FETCH';
export const WALLETS_DATA = 'wallets/WALLETS_DATA';
export const WALLETS_ERROR = 'wallets/WALLETS_ERROR';
export const WALLETS_RESET = 'wallets/WALLETS_RESET';

export const WALLETS_ADDRESS_FETCH = 'wallets/WALLETS_ADDRESS_FETCH';
export const WALLETS_ADDRESS_DATA = 'wallets/WALLETS_ADDRESS_DATA';
export const WALLETS_ADDRESS_ERROR = 'wallets/WALLETS_ADDRESS_ERROR';

export const WALLETS_WITHDRAW_FIAT_FETCH = 'wallets/WALLETS_WITHDRAW_FIAT_FETCH';
export const WALLETS_WITHDRAW_FIAT_DATA = 'wallets/WALLETS_WITHDRAW_FIAT_DATA';
export const WALLETS_WITHDRAW_FIAT_ERROR = 'wallets/WALLETS_WITHDRAW_FIAT_ERROR';

export const WALLETS_WITHDRAW_CCY_FETCH = 'wallets/WALLETS_WITHDRAW_CCY_FETCH';
export const WALLETS_WITHDRAW_CCY_DATA = 'wallets/WALLETS_WITHDRAW_CCY_DATA';
export const WALLETS_WITHDRAW_CCY_ERROR = 'wallets/WALLETS_WITHDRAW_CCY_ERROR';
