export const USER_ORDERS_HISTORY_FETCH = 'orders/USER_ORDERS_HISTORY_FETCH';
export const USER_ORDERS_HISTORY_DATA = 'orders/USER_ORDERS_HISTORY_DATA';
export const USER_ORDERS_HISTORY_ERROR = 'orders/USER_ORDERS_HISTORY_ERROR';
export const TEST_ORDERS_HISTORY_STATE = 'orders/TEST_ORDERS_HISTORY_STATE';

export const ORDERS_CANCEL_ALL_FETCH = 'orders/ORDERS_CANCEL_ALL_FETCH';
export const ORDERS_CANCEL_ALL_DATA = 'orders/ORDERS_CANCEL_ALL_DATA';
export const ORDERS_CANCEL_ALL_ERROR = 'orders/ORDERS_CANCEL_ALL_ERROR';

export const ORDERS_HISTORY_CANCEL_FETCH = 'orders/ORDERS_HISTORY_CANCEL_FETCH';
export const ORDERS_HISTORY_CANCEL_DATA = 'orders/ORDERS_HISTORY_CANCEL_DATA';
export const ORDERS_HISTORY_CANCEL_ERROR = 'orders/ORDERS_HISTORY_CANCEL_ERROR';
