export const USER_OPEN_ORDERS_FETCH = 'openOrders/USER_OPEN_ORDERS_FETCH';
export const USER_OPEN_ORDERS_DATA = 'openOrders/USER_OPEN_ORDERS_DATA';
export const USER_OPEN_ORDERS_ERROR = 'openOrders/USER_OPEN_ORDERS_ERROR';
export const USER_OPEN_ORDERS_APPEND = 'openOrders/USER_OPEN_ORDERS_APPEND';
export const USER_OPEN_ORDERS_UPDATE = 'openOrders/USER_OPEN_ORDERS_UPDATE';
export const USER_OPEN_ORDERS_RESET = 'openOrders/USER_OPEN_ORDERS_RESET';

export const OPEN_ORDERS_CANCEL_FETCH = 'openOrders/OPEN_ORDERS_CANCEL_FETCH';
export const OPEN_ORDERS_CANCEL_DATA = 'openOrders/OPEN_ORDERS_CANCEL_DATA';
export const OPEN_ORDERS_CANCEL_ERROR = 'openOrders/OPEN_ORDERS_CANCEL_ERROR';
