export const CHANGE_COLOR_THEME = 'colorTheme/CHANGE_COLOR_THEME';
export const TOGGLE_CHART_REBUILD = 'colorTheme/TOGGLE_CHART_REBUILD';
export const TOGGLE_MARKET_SELECTOR = 'colorTheme/TOGGLE_MARKET_SELECTOR';
export const TOGGLE_MOBILE_DEVICE = 'colorTheme/TOGGLE_MOBILE_DEVICE';
export const TOGGLE_SIDEBAR = 'colorTheme/TOGGLE_SIDEBAR';
export const TRIGGER_APPLY_WINDOW_ENVS = 'colorTheme/TRIGGER_APPLY_WINDOW_ENVS';
export const TOGGLE_ORDERS_PAIRS_SWITCHER = 'trading/TOGGLE_ORDERS_PAIRS_SWITCHER';
