export const FORGOT_PASSWORD_FETCH = 'password/FORGOT_PASSWORD_FETCH';
export const FORGOT_PASSWORD_ERROR = 'password/FORGOT_PASSWORD_ERROR';
export const PASSWORD_ERROR = 'password/PASSWORD_ERROR';

export const FORGOT_PASSWORD_REQUIRE_VERIFICATION = 'password/FORGOT_PASSWORD_REQUIRE_VERIFICATION';

export const FORGOT_PASSWORD_VERIFICATION_FETCH = 'password/FORGOT_PASSWORD_VERIFICATION_FETCH';
export const FORGOT_PASSWORD_VERIFICATION_SUCCESS = 'password/FORGOT_PASSWORD_VERIFICATION_SUCCESS';

export const CHANGE_PASSWORD_FETCH = 'password/CHANGE_PASSWORD_FETCH';
export const CHANGE_PASSWORD_SUCCESS = 'password/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'password/CHANGE_PASSWORD_ERROR';
