export const FORGOT_PASSWORD_FETCH = 'password/FORGOT_PASSWORD_FETCH';
export const FORGOT_PASSWORD_SUCCESS = 'password/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'password/FORGOT_PASSWORD_ERROR';

export const CHANGE_FORGOT_PASSWORD_FETCH = 'password/CHANGE_FORGOT_PASSWORD_FETCH';
export const CHANGE_FORGOT_PASSWORD_SUCCESS = 'password/CHANGE_FORGOT_PASSWORD_SUCCESS';

export const TEST_FORGOT_PASSWORD = 'password/TEST_FORGOT_PASSWORD';
