export const ORGANIZATION_ACCOUNTS_FETCH = 'organization/ACCOUNTS_FETCH';
export const ORGANIZATION_ACCOUNTS_DATA  = 'organization/ACCOUNTS_DATA';
export const ORGANIZATION_ACCOUNTS_ERROR = 'organization/ACCOUNTS_ERROR';
export const ORGANIZATION_ACCOUNT_SWITCH = 'organization/ACCOUNT_SWITCH';
export const ORGANIZATION_ACCOUNT_SWITCH_ERROR = 'organization/ACCOUNT_SWITCH_ERROR';
