export const CHANGE_COLOR_THEME = 'colorTheme/CHANGE_COLOR_THEME';
export const TOGGLE_SIDEBAR = 'colorTheme/TOGGLE_SIDEBAR';
export const TOGGLE_MARKET_SELECTOR = 'colorTheme/TOGGLE_MARKET_SELECTOR';
