export const COMMERCIAL_ACCOUNTS_FETCH = 'commercial/ACCOUNTS_FETCH';
export const COMMERCIAL_ACCOUNTS_DATA  = 'commercial/ACCOUNTS_DATA';
export const COMMERCIAL_ACCOUNTS_ERROR = 'commercial/ACCOUNTS_ERROR';
export const COMMERCIAL_ACCOUNT_SWITCH = 'commercial/ACCOUNT_SWITCH';
export const COMMERCIAL_ACCOUNT_SWITCH_ERROR = 'commercial/ACCOUNT_SWITCH_ERROR';
