/**
 * DO NOT EDIT THIS FILE
 *
 * To add or remove a plugin:
 * - Edit plugins.json
 * - Run yarn prepare:plugins
 */


// tslint:disable-next-line: no-empty-interface
export interface PluginsState {

}

export const pluginsInstances = {

};

export const pluginsLanguageMap = {

};

