/**
 * DO NOT EDIT THIS FILE
 *
 * To add or remove a plugin:
 * - Edit plugins.json
 * - Run yarn prepare:plugins
 */

import { IeoPlugin, IeoPluginState, ieoLanguageMap } from './ieo';

export interface PluginsState {
    ieo: IeoPluginState;
}
export const pluginsInstances = {
    ieo: IeoPlugin,
};
export const pluginsLanguageMap = {
    ...ieoLanguageMap,
};
