export const USER_ORDERS_HISTORY_FETCH = 'orders/USER_ORDERS_HISTORY_FETCH';
export const USER_ORDERS_HISTORY_DATA = 'orders/USER_ORDERS_HISTORY_DATA';
export const USER_ORDERS_HISTORY_ERROR = 'orders/USER_ORDERS_HISTORY_ERROR';
export const TEST_ORDERS_HISTORY_STATE = 'orders/TEST_ORDERS_HISTORY_STATE';
