export const GET_GEETEST_CAPTCHA_DATA = 'GEETEST_CAPTCHA/DATA';
export const GET_GEETEST_CAPTCHA_ERROR = 'GEETEST_CAPTCHA/ERROR';
export const GET_GEETEST_CAPTCHA_FETCH = 'GEETEST_CAPTCHA/FETCH';
export const GEETEST_CAPTCHA_SUCCESS_DATA = 'GEETEST_CAPTCHA_SUCCESS_DATA';
export const SHOULD_GEETEST_RESET_FETCH = 'SHOULD_GEETEST_RESET_FETCH';

export const RECAPTCHA_SUCCESS_DATA = 'RECAPTCHA_SUCCESS_DATA';

export const RESET_CAPTCHA_STATE = 'RESET_CAPTCHA_STATE';
