export const RANGER_CONNECT_FETCH = 'ranger/CONNECT_FETCH';
export const RANGER_CONNECT_DATA = 'ranger/CONNECT_DATA';
export const RANGER_CONNECT_ERROR = 'ranger/CONNECT_ERROR';
export const RANGER_DISCONNECT_FETCH = 'ranger/RANGER_DISCONNECT_FETCH';
export const RANGER_DISCONNECT_DATA = 'ranger/RANGER_DISCONNECT_DATA';
export const RANGER_DIRECT_WRITE = 'ranger/RANGER_DIRECT_WRITE';
export const RANGER_SUBSCRIPTIONS_DATA = 'ranger/RANGER_SUBSCRIPTIONS_DATA';
