export const ALERT_DELETE_ERROR = 'alert/DELETE_ERROR';
export const ALERT_ERROR_DATA = 'alert/ERROR_DATA';
export const ALERT_ERROR_PUSH = 'alert/ERROR_FETCH';
export const ALERT_DELETE_ERROR_BY_INDEX = 'alert/DELETE_ERROR_BY_INDEX';

export const ALERT_DELETE_SUCCESS = 'alert/DELETE_SUCCESS';
export const ALERT_SUCCESS_DATA = 'alert/SUCCESS_DATA';
export const ALERT_SUCCESS_PUSH = 'alert/SUCCESS_FETCH';
export const ALERT_DELETE_SUCCESS_BY_INDEX = 'alert/DELETE_SUCCESS_BY_INDEX';
